---
- hosts: authservers
  roles:
        - authserver

- hosts: serviceproviders
  roles: 
        - serviceprovider

- hosts: ldapservers
  roles: 
        - ldapserver
        - phpldapadmin

- hosts: nextcloudservers
  roles:
        - database
        - nextcloud
