---
ansible_user: root
nextcloud_version: 11.0.2
nextcloud_checksum: 104098067d0ca94d03babc4408923a55897f59030e0531fd557323e0c532802a
nextcloud_installdir: /var/nextcloud
database_name: "{{ nextcloud_db_name }}"
database_host: "{{ nextcloud_db_host }}"
database_user: "{{ nextcloud_db_username }}"
database_password: "{{ nextcloud_db_password }}"
server_name: nextcloud.stacken.kth.se

ldap_config:
  -  { key: "ldap_dn",                     value : "cn=nextcloud,ou=system_accounts,dc=stacken,dc=kth,dc=se" }
  -  { key: "ldap_agent_password",         value : "{{ ldap_nextcloud_password }}" }
  -  { key: "ldap_base",                   value : "dc=stacken,dc=kth,dc=se" }
  -  { key: "ldap_base_groups",            value : "dc=stacken,dc=kth,dc=se" }
  -  { key: "ldap_port",                   value : "389" }
  -  { key: "ldap_userfilter_objectclass", value : "inetOrgPerson\\nposixAccount" }
  -  { key: "ldap_login_filter",           value : "(&(|(objectclass=inetOrgPerson))(uid=%uid))" }
  -  { key: "ldap_display_name",           value : "displayName" }
  -  { key: "ldap_host",                   value : "130.237.234.189" }
  -  { key: "ldap_userlist_filter",        value : "(|(objectclass=inetOrgPerson)(objectclass=posixAccount))" }
  -  { key: "ldap_base_users",             value : "ou=users,dc=stacken,dc=kth,dc=se" }
  -  { key: "ldap_expert_username_attr",   value : "uid" }

saml_config:
  - { key: "idp-entityId",                value: "http://auth.stacken.kth.se/saml2/idp/metadata.php" }
  - { key: "general-uid_mapping",         value: "urn:oid:0.9.2342.19200300.100.1.1" }
  - { key: "idp-singleLogoutService.url", value: "http://auth.stacken.kth.se/saml2/idp/SingleLogoutService.php" }
  - { key: "idp-singleSignOnService.url", value: "http://auth.stacken.kth.se/saml2/idp/SSOService.php" }
  - { key: "type",                        value: "saml" }

samlIdpCert: >
  -----BEGIN CERTIFICATE-----
  MIIFnTCCA4WgAwIBAgIJANLFfj43CtEcMA0GCSqGSIb3DQEBCwUAMGUxCzAJBgNV
  BAYTAlNFMRIwEAYDVQQIDAlTdG9ja2hvbG0xEjAQBgNVBAcMCVN0b2NraG9sbTEQ
  MA4GA1UECgwHU3RhY2tlbjEcMBoGA1UEAwwTYXV0aC5zdGFja2VuLmt0aC5zZTAe
  Fw0xNzA0MTMxODUxNDFaFw0xODA0MTMxODUxNDFaMGUxCzAJBgNVBAYTAlNFMRIw
  EAYDVQQIDAlTdG9ja2hvbG0xEjAQBgNVBAcMCVN0b2NraG9sbTEQMA4GA1UECgwH
  U3RhY2tlbjEcMBoGA1UEAwwTYXV0aC5zdGFja2VuLmt0aC5zZTCCAiIwDQYJKoZI
  hvcNAQEBBQADggIPADCCAgoCggIBAOAhkm4ZtPLrzpNaj4evVVMeBwXajO8eWHxe
  wCkXysyCbBufU4rGuklrC7KF9+kweVEl6xcmUX56o1J/OI1N6BrA8TdjH+MymbZZ
  XmHN3R2xMKQh/ALEJZ48iKzHpr1OniRGhjxWfKFPfOfxfZ7kisO1+d8Z1gXDyqkw
  kFGX5OkJGDE2PEIzzuZqmoudz3x8RcOMGZvyNPtShxUGcVzjQjFWoTKZnK2PJ9Xj
  suGma3NKZNYIJd1jhvcjEJQGclAsSl9elSHJfoMd2hrsSsovs/niG38WVgvG+Cao
  AIJpuatVESodwgVDQASa1zZDTie/GPclXyOKnkSoGQCdSLTzPC9Td6Ime3lqYIoJ
  8DhF+6T614IXv/Y27bwdHk8m80fiAq9xNkiftMQv3cvtg5sZn3IUVqC3mxfhy18H
  u/4R+FxF8MMwBJxGjJAcwe89WJ1bKRPIM7z4kg9eEd8GXYxF5gj8XPLlFfOzYFhk
  0HY32tCO0Zelnc0oz7MiwhwxozQpbpdJcm9s4ks+XaoBga1/squzXjO3v7Lr235B
  t/i/ZzHnuniNUuyJqrGzh8OuVxDs4YVfGTnA9IUuz3g+itfXaXEuuGkOvFnOvzWg
  6+h+67Rk9phHAozkIWOjrkoHaQrdQpa6jc3C7YrkpkcRsUzCp2BxhOoThAkNhGsH
  Na/9PNT1AgMBAAGjUDBOMB0GA1UdDgQWBBSCsbG8mp45EftxXwmR12pJ1NWRRzAf
  BgNVHSMEGDAWgBSCsbG8mp45EftxXwmR12pJ1NWRRzAMBgNVHRMEBTADAQH/MA0G
  CSqGSIb3DQEBCwUAA4ICAQA71LaOruhQ5MEr4TDTg5lql9LKnx3vwSXSsBoQOiZm
  l8YgbNIpoUeNOpK5y5APBleetOkgg9LyWWzNwWLzPfwz+vqiQKtj5a+zPGYWs9nQ
  dPSa3aFpcXLxW3q+JvjsiOPgwYVvq4CFZEoPLWfL6xnv49bOS+xeVD6ui0OvHkOb
  3AACdRZEyS4qwmMx1v6BHGIKp1uO6peo52Hupyf7h3XLni87as7D6I7kr/phlxl6
  aL9yy55UN8hZTZ0Tyag++jQ7URm6n5IfiHZnURHjjqx4LsB1wnczI5aXxxogIFZL
  CUTvNPFPsm4/dKCL3TnOhb1rE5KsrgK/Xvh4Anw2mrfbXWXnSRnh11dohoXIF5R7
  3bfc9yKX/s6DWz7YJWpfdL+zqQqssvuquCLCtyei8Qpc8WMhEc19TgiHC6kXrlrv
  U7hPPvkl904eB8aztg6zWwEH5k3NKeSM3K5cx9vzzYP0hZ6b3UZ3Am+Wa+HH9gjB
  nyUT30KWhVbtukcXEVaYqUxMgIm4DqbvT+taf8iTGuADfIlCwcNCWmlMlAyqSN7M
  YQZLvn2hT2uw0ghIyDXZga1EWjcmAKoElkmFE7zIFhtqUv1SGsAg0X1k2yfZik0C
  1i6PZ4A7dyGjtj606STxt2fGX/PblXcYsdwypdkX6kpKUu5gRCDXoWMQaA383wi7
  1Q==
  -----END CERTIFICATE-----
