---
- name: install ldap
  apt: name={{ item }} state=present
  with_items:
          - slapd
          - ldap-utils
          - sasl2-bin

- name: inform of dpkg-reconfigure
  pause: prompt='Please run dpkg-reconfigure slapd manually before proceeding'
